name: Bandit Security Scan
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit  # Install Bandit explicitly
    - name: Run Bandit
      run: |
        bandit -r . -c .github/workflows/bandit_scan.yml --output bandit_report.html --format html


